name: Update Data to Private Repo

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

# এই অংশটি দুটি রানকে একসাথে হতে দেবে না (একটাই চলবে)
concurrency:
  group: update-db-job
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Public Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install firebase-admin

      - name: Fetch Data from Firebase
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python main.py

      - name: Push to Private Repo
        env:
          PAT: ${{ secrets.MY_PAT_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          
          # রিপো ডিরেক্টরি পরিষ্কার রাখার জন্য
          rm -rf temp_repo
          
          # ফ্রেশ ক্লোন করা
          git clone https://x-access-token:${PAT}@github.com/api00007/ALL-ROUNDER.git temp_repo
          
          cp ATV.json temp_repo/
          cd temp_repo
          
          git add ATV.json
          # যদি কোনো চেঞ্জ না থাকে তবুও এরর দেবে না
          git commit -m "Auto Update: $(date)" || exit 0
          
          # ফোর্স পুশ (Force Push) করা যাতে লক এরর না আসে
          git push origin main --force
