name: Update Data to Private Repo

on:
  schedule:
    - cron: '*/15 * * * *' # প্রতি ১৫ মিনিট পর পর
  workflow_dispatch: # ম্যানুয়ালি রান করার জন্য

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Public Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Fetch Data from Firebase
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python main.py

      - name: Push to Private Repo
        env:
          PAT: ${{ secrets.MY_PAT_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          # প্রাইভেট রিপোটি ক্লোন করা
          git clone https://x-access-token:${PAT}@github.com/ayvspop/ATV-DATA.git temp_repo
          # নতুন তৈরি হওয়া data.json ফাইলটি প্রাইভেট রিপোর ফোল্ডারে কপি করা
          cp data.json temp_repo/
          cd temp_repo
          git add data.json
          # যদি কোনো পরিবর্তন থাকে তবেই কেবল কমিট করবে
          git commit -m "Auto Update: $(date)" || exit 0
          git push origin main
